name: Lint

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
